global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'sinatra_app'
    static_configs:
      - targets: ['host.docker.internal:4000']

  - job_name: 'postgres'
    static_configs:
      - targets: ['host.docker.internal:9187']
